[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "monospace"

[server]
headless = true
enableXsrfProtection = false
port = 8501